version: 0.2

env:
    variables:
        S3_BUCKET: "codepipeline-javaconnect"
        APP_NAME: "JavaConnects"
        # BUILD_ENV : "prod"

phases:

  pre_build:

    commands:

        - echo Entered the install phase-
        - sudo apt-get update -y
        - sudo apt-get install -y software-properties-common
        - sudo add-apt-repository ppa:openjdk-r/ppa 
        - sudo apt-get update -y
        - sudo apt-get install -y maven
        - sudo apt-get install ssh -y 
        - sudo apt-get install git -y
        - git clone https://github.com/alisha101/ResultServer.git

  build:

    commands:
      - cd ResultServer
      - mvn clean
      - echo mvn clean done
      - mvn install
      - echo mvn install done

  post_build:

    commands:
      - echo Build completed on `date`
      - mvn package
      - ls target/Spring4AnnotationConfig-1.0-SNAPSHOT.war
      - ls /root/.m2/repository/com/outbottle/Spring4AnnotationConfig/1.0-SNAPSHOT
      - chmod 400 webapp.pem
      - ssh -o StrictHostKeyChecking=No -i /codebuild/output/src*/src/ResultServer/webapp.pem ec2-user@ec2-54-188-124-87.us-west-2.compute.amazonaws.com uptime 
      - scp -i /codebuild/output/src*/src/ResultServer/webapp.pem \/codebuild/output/src*/src/ResultServer/target/Spring4AnnotationConfig-1.0-SNAPSHOT.war ec2-user@ec2-54-188-124-87.us-west-2.compute.amazonaws.com:/var/lib/tomcat8/webapps/
      #- scp -i /codebuild/output/src*/src/ResultServer/webapp.pem \/codebuild/output/src*/src/ResultServer/target/*.war ec2-user@54.185.209.216:/home/ec2-user/
      #- aws s3 rm s3://codepipeline-javaconnect --recursive
      #- aws s3 cp /codebuild/output/src*/src/ResultServer/target/Spring4AnnotationConfig-1.0-SNAPSHOT.war s3://codepipeline-javaconnect
      #- mv /codebuild/output/src*/src/ResultServer/target/Spring4AnnotationConfig-1.0-SNAPSHOT.war /codebuild/output/src*/src/ResultServer/target/webapp.war
   
#   artifacts:
#     commands:
#       - target/*.war
